---
title: "vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This is a small test package that includes 5 functions.

## Functions

`fars_read`: This is a function that reads the .csv file in a compressed file into a data.frame in R.

`make_filename`: This is function that makes a standardized filename based on a specific year. For example, with input 2021, the output will be a character string "accident_2021.csv.bz2".

`fars_read_years`: This is a function that fetches the 'year' and 'MONTH' columns of the records of regarding fatal injuries, in the specific given years.

`fars_summarize_year`: This is a function that Summarize the counts of fatal injuries for each month, given specific years.

`fars_map_state`: This is a function that draws the map of the given state, and the records are shown on the map as dots according to their locations.

For more details, please visit the help files by typing `?function` in the console.



